### ISSUE TITLE
Nekonečné volání při chybě

### ISSUE THREAD

**Issue by kozubikmichal** [seznam/api-examples#3]
Zdravím,

https://github.com/seznam/api-examples/blob/a78470371c026f49ed2a198816ec1da83a992626/examples/ScriptGoogleAppsScript/AppsScript_basic.js#L115-L118

Chybí zde modifikace **retry** proměnné (konrétně přičtení **1**). Takhle se to při chybě bude volat pořád a pořád dokola, jelikož je retry nezměněné.

Regards
Michal

**Comment by ChocoTUx** [comment]
Mockrát děkuji za postřeh. Upravím.
